translation_edit_in_place_update:
    path: /_trans_edit_in_place/{configName}/{locale}
    methods: [POST]
    defaults:  { _controller: Translation\Bundle\Controller\EditInPlaceController::editAction }
