services:
  php_translation.catalogue_fetcher:
    class: Translation\Bundle\Service\CatalogueFetcher
    arguments: ["@translation.loader"]

  php_translation.catalogue_manager:
    class: Translation\Symfony\Catalogue\CatalogueManager
    arguments: ["%kernel.root_dir%/../"]

  php_translation.extractor:
    class: Translation\Extractor\Extractor

  php_translation.configuration_manager:
    class: Translation\Bundle\Service\ConfigurationManager
    arguments: [[]]

  php_translation.importer:
    class: Translation\Symfony\Importer
    arguments: ["@php_translation.extractor"]
