services:
  php_translation.catalogue_fetcher:
    class: Translation\Bundle\Catalogue\CatalogueFetcher
    arguments: ["@translation.loader"]

  php_translation.catalogue_writer:
    class: Translation\Bundle\Catalogue\CatalogueWriter
    arguments: ["@translation.writer", "%php_translation.default_locale%"]

  php_translation.storage.abstract:
    class: Translation\Bundle\Service\StorageService
    abstract: true
    arguments: ["@php_translation.catalogue_fetcher", "@php_translation.catalogue_writer", ~]

  php_translation.catalogue_manager:
    class: Translation\Bundle\Catalogue\CatalogueManager

  php_translation.extractor:
    class: Translation\Extractor\Extractor

  php_translation.configuration_manager:
    class: Translation\Bundle\Service\ConfigurationManager

  php_translation.importer:
    class: Translation\Bundle\Service\Importer
    arguments: ["@php_translation.extractor"]

  php_translation.cache_clearer:
    class: Translation\Bundle\Service\CacheClearer
    arguments: ["%kernel.cache_dir%", "@translator", "@filesystem"]

  php_translation.local_file_storage.abstract:
    class: Translation\SymfonyStorage\FileStorage
    abstract: true
    arguments: ["@translation.writer", "@translation.loader", ~, []]

  php_translation.storage.xlf_loader:
    class: Translation\SymfonyStorage\Loader\XliffLoader
    tags:
      - { name: translation.loader, alias: xlf, legacy-alias: xliff }

  php_translation.storage.xlf_dumper:
    class: Translation\SymfonyStorage\Dumper\XliffDumper
    tags:
      - { name: translation.dumper, alias: xlf, legacy-alias: xliff }

  php_translation.catalogue_counter:
    class: Translation\Bundle\Catalogue\CatalogueCounter
    arguments: []
