language: php

cache:
  directories:
    - $HOME/.composer/cache

branches:
  except:
    - /^analysis-.*$/
    - /^patch-.*$/

env:
  global:
    - TEST_COMMAND="composer test"
    - SYMFONY_PHPUNIT_VERSION="6.3"

matrix:
    fast_finish: true
    include:
          # Run test with code coverage
        - php: 7.2
          env: COVERAGE=true TEST_COMMAND="composer test-ci"

          # Test with lowest dependencies
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak" SYMFONY_PHPUNIT_VERSION="5.7"
        - php: 5.5
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak" SYMFONY_PHPUNIT_VERSION="5.7"

          # Test the latest stable release
        - php: 5.5
          env: SYMFONY_PHPUNIT_VERSION="5.7"
        - php: 5.6
          env: SYMFONY_PHPUNIT_VERSION="5.7"
        - php: 7.0
        - php: 7.1

          # Force some major versions of Symfony
        - php: 7.2
          env: DEPENDENCIES="dunglas/symfony-lock:^2 symfony/property-access:^2.8"
        - php: 7.2
          env: DEPENDENCIES="dunglas/symfony-lock:^3"
        - php: 7.2
          env: DEPENDENCIES="dunglas/symfony-lock:^4"
        - php: 7.0
          env: DEPENDENCIES="dunglas/symfony-lock:^2 twig/twig:^1.34 symfony/property-access:^2.8"

          # Latest commit to master
        - php: 7.2
          env: STABILITY="dev"

    allow_failures:
          # Dev-master is allowed to fail.
        - env: STABILITY="dev"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -z "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
    - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - $TEST_COMMAND

after_success:
    - if [[ $COVERAGE = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ $COVERAGE = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi

after_script:
    - wget http://tnyholm.se/reporter.phar
    - php reporter.phar build:upload
